In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# Use GPU units if available
print(device)

cpu


In [3]:
import numpy as np

# Load the .npy file
label_10 = np.load('/content/drive/MyDrive/DH302_Project/MTVital_main/MTHS/Data/label_10.npy')
sig_10 = np.load('/content/drive/MyDrive/DH302_Project/MTVital_main/MTHS/Data/signal_10.npy')

In [4]:
print(sig_10)
print('Number of samples in our signal: ',len(sig_10))
print(label_10)
print('Number of samples of our heart rate: ',len(label_10))

[[2.53124745e+02 2.50644145e+00 5.81781477e+01]
 [2.53289500e+02 2.45277199e+00 5.81860923e+01]
 [2.53236041e+02 2.50307774e+00 5.81471590e+01]
 ...
 [2.52633082e+02 2.26234086e-01 5.50807055e+01]
 [2.52620336e+02 2.26258681e-01 5.50482480e+01]
 [2.52576294e+02 2.07019676e-01 5.49957128e+01]]
Number of samples in our signal:  1800
[[69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [69. 95.]
 [70. 96.]
 [71. 97.]
 [72. 97.]
 [73. 97.]
 [72. 97.]
 [72. 97.]
 [72. 96.]
 [72. 96.]
 [72. 96.]
 [72. 96.]
 [72. 96.]
 [72. 96.]
 [72. 96.]
 [72. 96.]
 [72. 95.]
 [72. 95.]
 [72. 95.]
 [72. 95.]
 [72. 95.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [72. 94.]
 [76. 94.]
 [76. 94.]
 [76. 94.]
 [76. 94.]
 [76. 94.]]
Number

##Making directories to save our models and plots

In [5]:
import os

os.makedirs('content/Signal_Plots/', exist_ok=True)
os.makedirs('content/MTHS_Models/', exist_ok=True)
os.makedirs('content/BIDMC_Models/', exist_ok=True)
os.makedirs('content/MTHS_Results/', exist_ok=True)
os.makedirs('content/BIDMC_Results/', exist_ok=True)

##Plotting R, B and G values for some of the patient IDs

In [6]:
!python /content/drive/MyDrive/DH302_Project/MTVital_main/Code/plot_signal.py --patient_id=46 --dataset='mths' --savedir='content/Signal_Plots/'

Our sample's input signal sequence length is 1800
Figure(1200x2500)


#Training and Evaluation on MTHS Dataset

##Training the Models with different Loss functions

In [31]:
!python /content/drive/MyDrive/DH302_Project/MTVital_main/Code/train.py --mode='hr' --dataset='mths' --downsample=2 --timelen=10 --batchsize=32 --epochs=125 --testsize=0.2 --valsize=0.15 --savedir='content/MTHS_Models/'

Streaming output truncated to the last 5000 lines.
Epoch 44/125
10/10 - 0s - loss: 7.1541 - mae: 7.6304 - val_loss: 14.2176 - val_mae: 14.7176 - 102ms/epoch - 10ms/step
Epoch 45/125
10/10 - 0s - loss: 7.2148 - mae: 7.6963 - val_loss: 12.3761 - val_mae: 12.8712 - 154ms/epoch - 15ms/step
Epoch 46/125
10/10 - 0s - loss: 7.4576 - mae: 7.9413 - val_loss: 11.3633 - val_mae: 11.8630 - 151ms/epoch - 15ms/step
Epoch 47/125
10/10 - 0s - loss: 7.1400 - mae: 7.6222 - val_loss: 13.0502 - val_mae: 13.5396 - 97ms/epoch - 10ms/step
Epoch 48/125
10/10 - 0s - loss: 7.3012 - mae: 7.7856 - val_loss: 12.4948 - val_mae: 12.9859 - 108ms/epoch - 11ms/step
Epoch 49/125
10/10 - 0s - loss: 7.6261 - mae: 8.1078 - val_loss: 11.0851 - val_mae: 11.5843 - 158ms/epoch - 16ms/step
Epoch 50/125
10/10 - 0s - loss: 7.2226 - mae: 7.7041 - val_loss: 12.2382 - val_mae: 12.7213 - 95ms/epoch - 10ms/step
Epoch 51/125
10/10 - 0s - loss: 7.0619 - mae: 7.5407 - val_loss: 11.8161 - val_mae: 12.3096 - 85ms/epoch - 9ms/step
Epoch 52/

##Evaluating our Models

In [32]:
!python /content/drive/MyDrive/DH302_Project/MTVital_main/Code/evaluate.py --mode='hr' --dataset='mths' --downsample=2 --timelen=10  --testsize=0.2 --valsize=0.15 --savedir='content/MTHS_Models/' --saveplot='./'

2023-10-29 07:51:19.615768: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-29 07:51:19.615835: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-29 07:51:19.615880: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-29 07:51:19.628722: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-29 07:51:21.562388: W tensorflow/compiler/

#Training and Evaluation on BIDMC Dataset

##Training the Models with different Loss functions

---
- $\frac{30}{2} ≈ \frac{125}{8}$: Hence we downsample by 8

In [29]:
!python /content/drive/MyDrive/DH302_Project/MTVital_main/Code/train2.py --mode='hr' --dataset='bidmc' --downsample=8 --timelen=10 --batchsize=32 --epochs=10 --testsize=0.2 --valsize=0.15 --savedir='content/BIDMC_Models/'

2023-10-29 07:13:23.346271: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-29 07:13:23.346339: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-29 07:13:23.346395: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-29 07:13:23.361273: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-29 07:13:25.134205: W tensorflow/compiler/

##Evaluating our Models

In [26]:
!python /content/drive/MyDrive/DH302_Project/MTVital_main/Code/evaluate2.py  --mode='hr' --dataset='bidmc' --downsample=8 --timelen=10  --testsize=0.2 --valsize=0.15 --savedir='content/BIDMC_Models/' --saveplot='./'

2023-10-29 06:48:42.788245: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-29 06:48:42.788305: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-29 06:48:42.788352: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-29 06:48:42.798295: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-29 06:48:44.089605: W tensorflow/compiler/